# Generated by Django 6.0.1 on 2026-02-04 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('normalization', '0004_alter_normalizedcontent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrichedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enriched_payload', models.JSONField()),
                ('status', models.CharField(choices=[('INGESTED', 'Ingested'), ('NORMALIZED', 'Normalized'), ('ENRICHED', 'Enriched'), ('VALIDATED', 'Validated'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed')], default='ENRICHED', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('normalized_content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enriched', to='normalization.normalizedcontent')),
            ],
        ),
    ]
