# Generated by Django 6.0.1 on 2026-01-26 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0002_alter_rawcontent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_payload', models.JSONField()),
                ('processing_version', models.CharField(max_length=10, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=20)),
                ('error_message', models.TextField(null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('raw_content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_content', to='ingestion.rawcontent')),
            ],
        ),
    ]
