# Generated by Django 6.0.1 on 2026-01-26 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_alter_rawcontent_status'),
        ('normalization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normalizedcontent',
            name='processing_version',
        ),
        migrations.AlterField(
            model_name='normalizedcontent',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='normalizedcontent',
            name='processed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='normalizedcontent',
            name='raw_content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized', to='ingestion.rawcontent'),
        ),
        migrations.AlterField(
            model_name='normalizedcontent',
            name='status',
            field=models.CharField(default='SUCCESS', max_length=20),
        ),
    ]
