# Generated by Django 6.0.1 on 2026-01-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normalization', '0002_remove_normalizedcontent_processing_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalizedcontent',
            name='status',
            field=models.CharField(choices=[('INGESTED', 'Ingested'), ('NORMALIZED', 'Normalized'), ('ENROLLED', 'Enrolled'), ('VALIDATED', 'Validated'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed')], default='NORMALIZED', max_length=20),
        ),
    ]
