# Generated by Django 6.0.1 on 2026-02-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normalization', '0003_alter_normalizedcontent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalizedcontent',
            name='status',
            field=models.CharField(choices=[('INGESTED', 'Ingested'), ('NORMALIZED', 'Normalized'), ('ENRICHED', 'Enriched'), ('VALIDATED', 'Validated'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed')], default='INGESTED', max_length=20),
        ),
    ]
