# Generated by Django 6.0.1 on 2026-01-25 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('API', 'API'), ('FILE', 'File'), ('MANUAL', 'Manual')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('FAILED', 'Failed')], default=[('RECEIVED', 'Received'), ('FAILED', 'Failed')], max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingestion.contentsource')),
            ],
        ),
    ]
