# Generated by Django 6.0.1 on 2026-01-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawcontent',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('FAILED', 'Failed')], default='RECEIVED', max_length=20),
        ),
    ]
